const state={articles:[],query:'',source:'Alle bronnen',category:'Alle categorieën',saved:new Set(JSON.parse(localStorage.getItem('savedArticles')||'[]')),favoriteSources:new Set(JSON.parse(localStorage.getItem('favoriteSources')||'["Handbal Inside","Handbal Startpunt","Handbal.nl"]')),favoriteCategories:new Set(JSON.parse(localStorage.getItem('favoriteCategories')||'["TeamNL","Transfers","Super Handball League"]')),showImages:localStorage.getItem('showImages')!=='false',dark:localStorage.getItem('darkMode')==='true'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmtDate=d=>new Intl.DateTimeFormat('nl-NL',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(d));
const unique=k=>[...new Set(state.articles.map(a=>a[k]))];
function persist(){localStorage.setItem('savedArticles',JSON.stringify([...state.saved]));localStorage.setItem('favoriteSources',JSON.stringify([...state.favoriteSources]));localStorage.setItem('favoriteCategories',JSON.stringify([...state.favoriteCategories]));localStorage.setItem('showImages',String(state.showImages));localStorage.setItem('darkMode',String(state.dark));}
function filtered(){return state.articles.filter(a=>(state.source==='Alle bronnen'||a.source===state.source)&&(state.category==='Alle categorieën'||a.category===state.category)&&(`${a.title} ${a.summary} ${a.source} ${a.category}`.toLowerCase().includes(state.query.toLowerCase()))).sort((a,b)=>new Date(b.date)-new Date(a.date));}
function card(a){const saved=state.saved.has(a.id);return `<article class="news-card ${state.showImages?'':'no-image'}"><a class="thumb ${a.sourceKey}" href="${a.url}" target="_blank" rel="noopener" aria-label="Open ${a.title}">HN</a><div class="card-content"><div class="source-line"><span class="source-badge"></span>${a.source} · ${fmtDate(a.date)}</div><h3>${a.title}</h3><p class="summary">${a.summary}</p><div class="card-actions"><a class="read-link" href="${a.url}" target="_blank" rel="noopener">Lees bij de bron →</a><button class="save-button ${saved?'saved':''}" data-save="${a.id}" aria-label="Opslaan">${saved?'♥':'♡'}</button></div></div></article>`}
function renderHero(){const a=filtered().find(x=>x.featured)||filtered()[0];$('#hero').innerHTML=a?`<a class="hero" href="${a.url}" target="_blank" rel="noopener" style="display:block"><div class="hero-art"></div><div class="hero-ball"></div><div class="hero-content"><span class="eyebrow">${a.category}</span><h1>${a.title}</h1><div class="hero-meta">${a.source} · ${fmtDate(a.date)} · Lees bij de bron →</div></div></a>`:''}
function renderList(sel,items){$(sel).innerHTML=items.length?items.map(card).join(''):`<div class="empty">Geen berichten gevonden.</div>`}
function render(){const list=filtered();renderHero();renderList('#newsList',list);$('#resultCount').textContent=`${list.length} berichten`;const fy=state.articles.filter(a=>state.favoriteSources.has(a.source)||state.favoriteCategories.has(a.category));renderList('#forYouList',fy);renderList('#savedList',state.articles.filter(a=>state.saved.has(a.id)));$('#categoryGrid').innerHTML=unique('category').map(c=>`<button class="category-card" data-category-open="${c}"><strong>${c}</strong><span>${state.articles.filter(a=>a.category===c).length} berichten</span></button>`).join('');bindDynamic();}
function chips(){const sources=['Alle bronnen',...unique('source')];const cats=['Alle categorieën',...unique('category')];$('#sourceFilters').innerHTML=sources.map(x=>`<button class="chip ${state.source===x?'active':''}" data-source="${x}">${x}</button>`).join('');$('#categoryFilters').innerHTML=cats.map(x=>`<button class="chip ${state.category===x?'active':''}" data-category="${x}">${x}</button>`).join('');}
function settings(){const row=(type,x,set)=>`<label class="switch-row"><span>${x}</span><input type="checkbox" data-${type}="${x}" ${set.has(x)?'checked':''}></label>`;$('#sourceSettings').innerHTML=unique('source').map(x=>row('favsource',x,state.favoriteSources)).join('');$('#categorySettings').innerHTML=unique('category').map(x=>row('favcategory',x,state.favoriteCategories)).join('');$('#imagesToggle').checked=state.showImages;$('#darkToggle').checked=state.dark;}
function applyTheme(){document.body.classList.toggle('dark',state.dark);document.body.classList.toggle('images-off',!state.showImages)}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1600)}
function bindDynamic(){$$('[data-save]').forEach(b=>b.onclick=()=>{state.saved.has(b.dataset.save)?state.saved.delete(b.dataset.save):state.saved.add(b.dataset.save);persist();render();toast(state.saved.has(b.dataset.save)?'Artikel opgeslagen':'Verwijderd uit opgeslagen')});$$('[data-category-open]').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;chips();showView('homeView');render()})}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
async function init(){try{state.articles=await fetch('data/articles.json',{cache:'no-store'}).then(r=>r.json())}catch(e){$('#newsList').innerHTML='<div class="empty">Nieuws kon niet worden geladen. Ververs de pagina.</div>';return}applyTheme();chips();settings();render();$('#updatedText').textContent='Bijgewerkt: 31 juli 2026, 21:45';$('#searchInput').oninput=e=>{state.query=e.target.value;render()};$('#filterButton').onclick=()=>$('#filterPanel').classList.toggle('hidden');$('#resetFilters').onclick=()=>{state.source='Alle bronnen';state.category='Alle categorieën';state.query='';$('#searchInput').value='';chips();render()};$('#sourceFilters').onclick=e=>{if(e.target.dataset.source){state.source=e.target.dataset.source;chips();render()}};$('#categoryFilters').onclick=e=>{if(e.target.dataset.category){state.category=e.target.dataset.category;chips();render()}};$$('.nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#themeButton').onclick=()=>{state.dark=!state.dark;persist();applyTheme();settings()};$('#darkToggle').onchange=e=>{state.dark=e.target.checked;persist();applyTheme()};$('#imagesToggle').onchange=e=>{state.showImages=e.target.checked;persist();applyTheme();render()};$('#sourceSettings').onchange=e=>{const x=e.target.dataset.favsource;if(x){e.target.checked?state.favoriteSources.add(x):state.favoriteSources.delete(x);persist();render()}};$('#categorySettings').onchange=e=>{const x=e.target.dataset.favcategory;if(x){e.target.checked?state.favoriteCategories.add(x):state.favoriteCategories.delete(x);persist();render()}};if('serviceWorker' in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{})}
document.addEventListener('DOMContentLoaded',init);
