[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/.netlify/functions/news"
  [headers.values]
    Cache-Control = "public, max-age=0, s-maxage=1800, stale-while-revalidate=3600"
